// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA9e_BRfVRGaDzPyM4G52WhaZ7se_A_PYU",
    authDomain: "todoapp-9bbe4.firebaseapp.com",
    projectId: "todoapp-9bbe4",
    storageBucket: "todoapp-9bbe4.firebasestorage.app",
    messagingSenderId: "109859695926",
    appId: "1:109859695926:web:a0be51d9a409296fc99797",
    measurementId: "G-8T8PSM3WB9",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYUwM6ynMVXIRMtx7js6oInWsFgXP29d4',
    appId: '1:109859695926:android:a053b21afe475d86c99797',
    messagingSenderId: '109859695926',
    projectId: 'todoapp-9bbe4',
    storageBucket: 'todoapp-9bbe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIUqKUcVJprQ-2DoXJIPbDiMDbQ4mZxmU',
    appId: '1:109859695926:ios:9ae1bba685daf259c99797',
    messagingSenderId: '109859695926',
    projectId: 'todoapp-9bbe4',
    storageBucket: 'todoapp-9bbe4.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIUqKUcVJprQ-2DoXJIPbDiMDbQ4mZxmU',
    appId: '1:109859695926:ios:9ae1bba685daf259c99797',
    messagingSenderId: '109859695926',
    projectId: 'todoapp-9bbe4',
    storageBucket: 'todoapp-9bbe4.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyA9e_BRfVRGaDzPyM4G52WhaZ7se_A_PYU",
    authDomain: "todoapp-9bbe4.firebaseapp.com",
    projectId: "todoapp-9bbe4",
    storageBucket: "todoapp-9bbe4.firebasestorage.app",
    messagingSenderId: "109859695926",
    appId: "1:109859695926:web:7696e236dbf79819c99797",
    measurementId: "G-FTL2P8T61P",
  );
}
